'''
Created on 22.06.2026

@author: Wolfg
'''

sql_insert_currency = f"""
INSERT INTO currency (iso_code, name, numeric_code, minor_unit, symbol, country, enabled) VALUES
('EUR','Euro','978',2,'€','Eurozone',1),
('USD','US Dollar','840',2,'$','United States',1),
('JPY','Japanese Yen','392',0,'¥','Japan',1),
('GBP','Pound Sterling','826',2,'£','United Kingdom',1),
('CHF','Swiss Franc','756',2,'CHF','Switzerland',1),
('CNY','Chinese Yuan','156',2,'¥','China',0),
('INR','Indian Rupee','356',2,'₹','India',0),
('AUD','Australian Dollar','36',2,'$','Australia',1),
('CAD','Canadian Dollar','124',2,'$','Canada',1),
('NZD','New Zealand Dollar','554',2,'$','New Zealand',0),
('SEK','Swedish Krona','752',2,'kr','Sweden',0),
('NOK','Norwegian Krone','578',2,'kr','Norway',0),
('DKK','Danish Krone','208',2,'kr','Denmark',0),
('PLN','Polish Zloty','985',2,'zł','Poland',0),
('CZK','Czech Koruna','203',2,'Kč','Czech Republic',0),
('HUF','Hungarian Forint','348',2,'Ft','Hungary',0),
('RON','Romanian Leu','946',2,'lei','Romania',0),
('BGN','Bulgarian Lev','975',2,'лв','Bulgaria',0),
('HRK','Croatian Kuna','191',2,'kn','Croatia',0),
('TRY','Turkish Lira','949',2,'₺','Turkey',0),
('RUB','Russian Ruble','643',2,'₽','Russia',0),
('ISK','Icelandic Króna','352',0,'kr','Iceland',0),
('BRL','Brazilian Real','986',2,'R$','Brazil',1),
('MXN','Mexican Peso','484',2,'$','Mexico',0),
('ARS','Argentine Peso','32',2,'$','Argentina',0),
('CLP','Chilean Peso','152',0,'$','Chile',0),
('COP','Colombian Peso','170',2,'$','Colombia',0),
('PEN','Peruvian Sol','604',2,'S/','Peru',0),
('UYU','Uruguayan Peso','858',2,'$','Uruguay',0),
('PYG','Paraguayan Guarani','600',0,'₲','Paraguay',0),
('BOB','Bolivian Boliviano','68',2,'Bs','Bolivia',0),
('GTQ','Guatemalan Quetzal','320',2,'Q','Guatemala',0),
('CRC','Costa Rican Colón','188',2,'₡','Costa Rica',0),
('HNL','Honduran Lempira','340',2,'L','Honduras',0),
('NIO','Nicaraguan Córdoba','558',2,'C$','Nicaragua',0),
('PAB','Panamanian Balboa','590',2,'B/.','Panama',0),
('JMD','Jamaican Dollar','388',2,'$','Jamaica',0),
('TTD','Trinidad and Tobago Dollar','780',2,'$','Trinidad and Tobago',0),
('BBD','Barbadian Dollar','52',2,'$','Barbados',0),
('BSD','Bahamian Dollar','44',2,'$','Bahamas',0),
('ZAR','South African Rand','710',2,'R','South Africa',0),
('EGP','Egyptian Pound','818',2,'£','Egypt',0),
('MAD','Moroccan Dirham','504',2,'د.م.','Morocco',0),
('TND','Tunisian Dinar','788',3,'د.ت','Tunisia',0),
('DZD','Algerian Dinar','12',2,'د.ج','Algeria',0),
('KES','Kenyan Shilling','404',2,'KSh','Kenya',0),
('UGX','Ugandan Shilling','800',0,'USh','Uganda',0),
('TZS','Tanzanian Shilling','834',2,'TSh','Tanzania',0),
('GHS','Ghanaian Cedi','936',2,'₵','Ghana',0),
('ETB','Ethiopian Birr','230',2,'Br','Ethiopia',0),
('NGN','Nigerian Naira','566',2,'₦','Nigeria',0),
('XOF','West African CFA Franc','952',0,'CFA','WAEMU',0),
('XAF','Central African CFA Franc','950',0,'FCFA','Central Africa',0),
('XPF','CFP Franc','953',0,'₣','French Pacific',0),
('KRW','South Korean Won','410',0,'₩','South Korea',0),
('SGD','Singapore Dollar','702',2,'$','Singapore',0),
('HKD','Hong Kong Dollar','344',2,'$','Hong Kong',0),
('TWD','New Taiwan Dollar','901',2,'NT$','Taiwan',0),
('THB','Thai Baht','764',2,'฿','Thailand',0),
('MYR','Malaysian Ringgit','458',2,'RM','Malaysia',0),
('IDR','Indonesian Rupiah','360',2,'Rp','Indonesia',0),
('PHP','Philippine Peso','608',2,'₱','Philippines',0),
('VND','Vietnamese Dong','704',0,'₫','Vietnam',0),
('ILS','Israeli New Shekel','376',2,'₪','Israel',0),
('AED','UAE Dirham','784',2,'د.إ','United Arab Emirates',0),
('SAR','Saudi Riyal','682',2,'﷼','Saudi Arabia',0),
('QAR','Qatari Riyal','634',2,'﷼','Qatar',0),
('KWD','Kuwaiti Dinar','414',3,'د.ك','Kuwait',0),
('BHD','Bahraini Dinar','48',3,'.د.ب','Bahrain',0),
('OMR','Omani Rial','512',3,'﷼','Oman',0),
('JOD','Jordanian Dinar','400',3,'د.ا','Jordan',0),
('LKR','Sri Lankan Rupee','144',2,'Rs','Sri Lanka',0),
('PKR','Pakistani Rupee','586',2,'₨','Pakistan',0),
('BDT','Bangladeshi Taka','50',2,'৳','Bangladesh',0),
('FJD','Fijian Dollar','242',2,'$','Fiji',0),
('PGK','Papua New Guinean Kina','598',2,'K','Papua New Guinea',0),
('WST','Samoan Tala','882',2,'T','Samoa',0),
('TOP','Tongan Paʻanga','776',2,'T$','Tonga',0),
('VUV','Vanuatu Vatu','548',0,'VT','Vanuatu',0),
('XDR','Special Drawing Rights','960',2,'SDR','IMF',0),
('XAU','Gold (troy ounce)','959',0,'XAU','Precious Metal',0),
('XAG','Silver (troy ounce)','961',0,'XAG','Precious Metal',0),
('XPT','Platinum','962',0,'XPT','Precious Metal',0),
('XPD','Palladium','964',0,'XPD','Precious Metal',0),
('PCT  ','Percent',NULL,2,'%','Bond Price Percentage',1);
"""
